# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
sudo: required

services:
  - docker

branches:
  only:
    - master

install: true

language: minimal

script: ./travis/start-docker-container.sh
